### PR TITLE
links.yml: remove IRC

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
As a part of https://forum.ansible.com/t/proposal-consolidating-ansible-discussion-platforms/6812

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME
CONTRIBUTING.md

### CODE REVIEW

**Comment by Andersson007** [comment]
ready for review

**Review by felixfontein — CHANGES_REQUESTED** [review]
Adding a negative review since https://forum.ansible.com/t/6812 hasn't been decided yet.

**Comment by felixfontein** [comment]
#962 removes the mailing list reference.

**Comment by Andersson007** [comment]
@felixfontein rebased, PTAL

**Comment by Andersson007** [comment]
@felixfontein the poll [results](https://forum.ansible.com/t/proposal-consolidating-ansible-discussion-platforms/6812/38?u=andersson007) are ready.
Looks like the community is OK with removal of IRC whatsoever or keeping refs to active rooms. Anyway, it's up to maintainers of particular projects to decide what to use, so please merge or close the PR. Thanks

**Comment by felixfontein** [comment]
I think for now, let's keep the IRC reference. Thanks for your work on this!

**Pull request closed without merging**
