### PR TITLE
CI: Stop using ansible-galaxy collection install to install a collection

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
ansible/galaxy#2429 is getting to a point where it is a huge PITA. To work around it, we directly clone the corresponding git repositories.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
CI

### CODE REVIEW

**Comment by felixfontein** [comment]
The group 4 failures are expected. I'm working on that in #112 (which is complicated by Galaxy failing all the time, so I'll merge this as soon as the rest passes and someone approves).

**Comment by felixfontein** [comment]
CC @Andersson007

**Comment by felixfontein** [comment]
This is really needed, right now I have to restart almost every CI run in this collection...

**Review by Andersson007 — APPROVED** [review]
LGTM, thanks!

**Comment by felixfontein** [comment]
@Andersson007 thanks for reviewing!

**Pull request merged**
