### PR TITLE
Move common utility code to plugins.module_utils.util

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Subset of #387.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
various modules and plugins

### CODE REVIEW

**Review by briantist — COMMENTED** [review]
You may want to consider making the util internal so that "breaking" changes in the util interface that don't break things in the user-facing code (because it's changed at the same time), will not need to be a breaking change in the collection.

Details in this comment (it's your minimized comment, need to expand to see it):
- https://github.com/ansible/community/issues/539#issuecomment-780839686

(I did this for all of mine, since I don't expect or want any other collections to be depending on them)

**Comment by briantist** [comment]
Ah, I've just realized that that stuff was mostly (completely?) moved from a different module_util, not from the modules themselves. I guess technically this is a breaking change then, though I'm personally not interested in being a stickler about that when we have a pretty good idea of when a module util is used internally only... I don't have such an idea on this one but I trust your judgement on it.

**Comment by felixfontein** [comment]
It's not a breaking change because it's still available in the other module_utils (due import).

If you move a function (or class) `x` from module_utils `a` to module_utils `b` and add `from b import x` into `a`, `x` is now available from both.

**Review by briantist — APPROVED** [review]
I see, I missed that detail

**Pull request merged**
