### PR TITLE
Improve and fix tests

### LINKED ISSUE #35: Nightly CI failed because of Docker Hub limitations
##### SUMMARY
In this run: https://app.shippable.com/github/ansible-collections/community.docker/runs/68/12/console and two others, CI failed because of [Docker Hub's rate limiting](https://www.docker.com/increase-rate-limits?utm_source=docker&utm_medium=web%20referral&utm_campaign=pull%20limits%20hub%20home%20page&utm_budget=).

``"Error looking for an image named alpine:3.8: 429 Client Error: Too Many Requests (\"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit\")"``

I guess we'll have to reorganize the images a bit, and push/pull some to/from quay.io instead.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
CI

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #35. Also makes it easier to use other images for testing by parameterizing them with definitions in one place.

##### ISSUE TYPE
- Test Pull Request

##### COMPONENT NAME
CI

### CODE REVIEW

**Comment by WojciechowskiPiotr** [comment]
shipit

**Review by WojciechowskiPiotr — APPROVED** [review]

**Comment by felixfontein** [comment]
@WojciechowskiPiotr thanks for reviewing! Since you have commit rights, do you want to press the Big Green Button? :)

**Comment by WojciechowskiPiotr** [comment]
I was a pleasure to press it ;)

**Comment by felixfontein** [comment]
@WojciechowskiPiotr congrats for your first merge in this repo ;)

**Pull request merged**
