### PR TITLE
docker_plugin: configure plugin after installing it

### LINKED ISSUE #118: docker_plugin driver options not configure plugin
##### SUMMARY
Like in example below in official [documentation](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_plugin_module.html#return-values) , there will no be any params in config through `plugin_options`

`docker plugin inspect weaveworks/net-plugin:latest_release | grep PASSWORD`

```                  
 "Name": "WEAVE_PASSWORD",
 "WEAVE_PASSWORD=",
```

```
- name: Install a plugin with options
  community.docker.docker_plugin:
    name: weaveworks/net-plugin:latest_release
    plugin_options:
      IPALLOC_RANGE: "10.32.0.0/12"
      WEAVE_PASSWORD: "PASSWORD"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.docker.docker_plugin

##### ANSIBLE VERSION

```paste below
2.10.7
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 20.04

##### STEPS TO REPRODUCE

```
- name: Install a plugin
      community.docker.docker_plugin:
        plugin_name: "vieux/sshfs"
        plugin_options:
          sshkey.source: "/tmp/.ssh/"
        state: enable
```

```yaml

```

##### EXPECTED RESULTS

`docker plugin inspect vieux/sshfs`

```
.....
            ],
            "Mounts": [
                {
                    "Description": "",
                    "Destination": "/mnt/state",
                    "Name": "state",
                    "Options": [
                        "rbind"
                    ],
                    "Settable": [
                        "source"
                    ],
                    "Source": "/var/lib/docker/plugins/",
                    "Type": "bind"
                },
                {
                    "Description": "",
                    "Destination": "/root/.ssh",
                    "Name": "sshkey",
                    "Options": [
                        "rbind"
                    ],
                    "Settable": [
                        "source"
                    ],
                    "Source": "/tmp/.ssh/",
                    "Type": "bind"
                }
            ]
        }
    }
]
```

##### ACTUAL RESULTS

`docker plugin inspect vieux/sshfs`

```
.......
              },
                {
                    "Description": "",
                    "Destination": "/root/.ssh",
                    "Name": "sshkey",
                    "Options": [
                        "rbind"
                    ],
                    "Settable": [
                        "source"
                    ],
                    "Source": "",
                    "Type": "bind"
                }
            ]
        }
    }
]
```

```paste below

```

### PR DESCRIPTION
**Pull request by felixfontein**
###### SUMMARY
Hopefully fixes #118.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_plugin

### CODE REVIEW

**Review by Andersson007 — APPROVED** [review]
```
$ grep -r plugin_options tests/integration/
tests/integration/targets/docker_plugin/tasks/tests/basic.yml:# Integration-Test with plugin_options is in TODO-List
```
heh
I think it's time we did it:)

If you test it locally and this change fixes the issue, LGTM

**Comment by felixfontein** [comment]
I can't test it locally since I don't use docker plugins. Unfortunately @Pavlentio never reacted to my questions, so I don't know whether this actually works.

**Comment by Andersson007** [comment]
LGTM

**Comment by felixfontein** [comment]
@Andersson007 thanks for reviewing!

**Pull request merged**
