### PR TITLE
docker_container: add default_host_ip option

### LINKED ISSUE #70: IPv6 port mapping broken with docker 20.10.2
##### SUMMARY
The `docker_container` module set an IP**v4** as [default host](https://github.com/ansible-collections/community.docker/blob/5072b7d1c31bacb3b06174d1f4a39d1d4afc7950/plugins/modules/docker_container.py#L1673) for `published_ports`.
Since the last version of docker (20.10.2) and recent changes (see [here](https://github.com/moby/libnetwork/issues/2607)), `0.0.0.0` doesn't bind on IPv6 anymore.

So, containers defined like the following loose their dual stack binding when upgrading to docker 20.10.2. If containers were defined with the docker cli, upgrade would be transparent.
```yaml
- docker_container:
    image: nginx
    name: foo
    published_ports:
    - 8080:80
```

A user side workaround could to be force definition of a listening IPv6 host like the following.
This require to known if host is supporting IPv6 instead of having it configured automatically depending of the host support of an IPv6 stack.
N.B: I didn't find a way to push an empty string as host in `published_ports`.
```yaml
    published_ports:
    - "0.0.0.0:8080:80"
    - "[::]:8080:80"
```

The difference between containers can be seen with the following commands:
```
# create a bar container from cli
$ docker run --publish 8081:80 --name bar -d nginx

$ docker inspect bar -f='{{.HostConfig.PortBindings}}'        
map[80/tcp:[{ 8081}]]

$ docker inspect foo -f='{{.HostConfig.PortBindings}}'
map[80/tcp:[{0.0.0.0 8080}]]
```

##### SOLUTION

I suggest to mimic the docker cli behavior and change the default Host to an empty string.
This way, when users doesn't set an host for `published_ports`, **dockerd** chooses the correct binding.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = /home/seblu/scm/infra/ansible.cfg
  configured module search path = ['/home/seblu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
```
##### OS / ENVIRONMENT

Arch Linux

##### STEPS TO REPRODUCE
- Have an IPv6 host
- Upgrade to docker > 20.10

A simple container like this is enough.

```yaml
- docker_container:
    image: nginx
    name: foo
    published_ports:
    - 8080:80
```

##### EXPECTED RESULTS
Docker container should be bound to IPv6 host addresses.
```
$ ss -tulpn|grep docker-proxy
tcp   LISTEN 0      4096                            0.0.0.0:8080       0.0.0.0:*    users:(("docker-proxy",pid=678243,fd=4))                                                                                                           
tcp   LISTEN 0      4096                               [::]:8080          [::]:*    users:(("docker-proxy",pid=678248,fd=4))

$ curl http://[2001:ac1d:bee:face:beef::1]:8080
<!DOCTYPE html>
<html>
...
```
This ouput is with docker > 20.10. With older version the binding is on `*:8080`.

##### ACTUAL RESULTS
```
$ ss -tulpn|grep docker-proxy
tcp   LISTEN 0      4096                            0.0.0.0:8080       0.0.0.0:*    users:(("docker-proxy",pid=682889,fd=4))                                                                                                           
                                                                                     
$ curl http://[2001:ac1d:bee:face:beef::1]:8080
curl: (7) Failed to connect to 2001:ac1d:bee:face:beef::1 port 8080: Connection refused


```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #70.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
docker_container

### CODE REVIEW

**Comment by felixfontein** [comment]
@seblu if you have time, feel free to test this :) I tested it locally with Docker CE 20.10.2, and for my simple test case it worked.

**Comment by seblu** [comment]
Yes, this will make my ansible collection fu be better ! I needed to learn how to overrides collection.

So, it looks like it works as expected.

```
TASK [community.docker.docker_container] *****************************************************************************************************************************************************
task path: /home/seblu/scm/infra/playbooks/test.yml:6
--- before
+++ after
@@ -2,11 +2,7 @@
     "expected_ports": {
         "25826/udp": [
             {
-                "HostIp": "::",
-                "HostPort": "25826"
-            },
-            {
-                "HostIp": "0.0.0.0",
+                "HostIp": "",
                 "HostPort": "25826"
             }
         ]
```

**Comment by felixfontein** [comment]
@WojciechowskiPiotr can you take a quick look? If we can get this merged and a new version released by next ~Tuesday, this should get included in the next Ansible 2.10.6 release (which will probably be the last 2.10.x release).

**Comment by WojciechowskiPiotr** [comment]
> @WojciechowskiPiotr can you take a quick look? If we can get this merged and a new version released by next ~Tuesday, this should get included in the next Ansible 2.10.6 release (which will probably be the last 2.10.x release).

**Comment by WojciechowskiPiotr** [comment]
Merged, closed by accident, sorry. 

Shouldn't we include this option in examples? I mean this is quite a significant change that needs to be made in playbooks when migrating to 20.10 so maybe some example(s) should help the users to not make mistakes? I know they should read the documentation, but still

**Comment by felixfontein** [comment]
@WojciechowskiPiotr makes sense. Feel free to create a PR for that!

**Pull request merged**
